Repository rancher/wins, pull requests merged in 2022-04, with the labels that each got.

#106 Creating an uninstall script for the Wins agent.
  uninstall.ps1
Labels: enhancement, area/windows

#107 go fmt and gitignore additions
  .gitignore
  pkg/concierge/concierge.go
  pkg/profilings/dump.go
Labels: bug

#108 bump version of csi-proxy in README to support Windows Server 2022
  README.md
Labels: bug, [zube]: Review, team/area4

#111 Add TLS and CA Certificate support for wins
  README.md
  cmd/server/config/config.go
  pkg/csiproxy/csi.go
  pkg/defaults/variable.go
  pkg/tls/tls.go
Labels: bug, [zube]: Review, area/windows, team/area4

#112 fix import cycle, enhance stackdump info message
  cmd/cmds/tools.go
  cmd/server/config/config.go
  pkg/csiproxy/csi.go
  pkg/profilings/stack.go
  pkg/tls/tls.go
Labels: bug, area/windows, team/area4
